name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Check Python version
      run: python --version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run the application in the background
      run: python app.py &

    - name: Run unit tests (simple curl check)
      run: |
        sleep 5
        response=$(curl --write-out "%{http_code}" --silent --output /dev/null http://localhost:5000/)
        if [ "$response" -ne 200 ]; then
          echo "Unit test failed: Unexpected HTTP response $response"
          exit 1
        else
          echo "Unit test passed"
        fi

  package:
    runs-on: ubuntu-22.04
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker image
      run: docker build -t rivka48651/entrytracker:latest .

    - name: Push image to Docker Hub
      run: docker push rivka48651/entrytracker:latest



