name: CI/CD for EntryTracker

on:
  push:
    branches:
      - main

jobs:
  build-test-package-e2e-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python 3.10 🐍

      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run application in background
      run: |
        python app.py &
        sleep 5

    - name: Run unit test (curl)
      run: |
        curl --fail http://localhost:5000/ || exit 1

    - name: Build Docker image
      run: |
        docker build -t ghcr.io/${{ github.repository_owner }}/entrytracker:latest .

    - name: Docker Compose up for E2E tests
      run: |
        docker-compose up -d
        sleep 10
        curl --fail http://localhost:5000/ || exit 1
        docker-compose down

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Push Docker image to GHCR
      run: |
        docker push ghcr.io/${{ github.repository_owner }}/entrytracker:latest
