name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run the application in the background
      run: |
        python app.py &

    - name: Run unit tests (simple curl check)
      run: |
        sleep 5  # מחכה שהשרת יאתחל
        response=$(curl --write-out "%{http_code}" --silent --output /dev/null http://localhost:5000/)
        if [ "$response" -ne 200 ]; then
          echo "Unit test failed: Unexpected HTTP response $response"
          exit 1
        else
          echo "Unit test passed"
        fi
